# Generated by Django 5.0.8 on 2024-09-03 21:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 7), ('embed_block', 8), ('card', 12), ('featured_posts', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'reqired': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 6)]], {}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed. For example, https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media'}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('heading', 9), ('text', 10), ('image', 11)]], {'group': 'Sections'}), 13: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 14: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blog.BlogPage']}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('heading', 9), ('text', 13), ('posts', 15)]], {'group': 'Sections'})}, help_text='Use this section to list your projects and skills.'),
        ),
    ]
